### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by jsulmont**
Dependencies updated, as of Aug 22nd 2016

### CODE REVIEW

**Comment by aphyr** [comment]
Hey, thanks for this! Uh, I haven't worked on this code in a couple years, and the tests fail to compile right now, so I'm gonna hold off on cutting a release until I can... figure out what's broken.

**Comment by aphyr** [comment]
Hmm, yeah, `lein test :all` throws a billion errors from something in coerce.clj. Did the tests pass for you?

**Comment by jsulmont** [comment]
Yes, I’ve noticed that the “lein test :perf” command took a ridiculous amount of time to run but last time I ran it, it eventually returned with reasonable performance ratios between instaparse and antlr4, so I figured the problem was elsewhere and carried on, since everything else seems to be working with my project ...

**Comment by aphyr** [comment]
Yeah, :perf should be slow (it needs a statistically significant sample) but I'm concerned about the tests in core_test not passing. Any idea there?

**Comment by jsulmont** [comment]
Ah I’ll have a look tomorrow morning (in Berlin Germany).
That shouldn’t be a big deal — sorry

**Comment by aphyr** [comment]
Many thanks! I apologize that I can't dig into it myself right now--running behind on work for my clients at the moment. Happy to cut a release as soon as we've got passing tests.

**Comment by jsulmont** [comment]
No worries at all. My bad — shouldn’t have pull requested prior to checking the tests (just ran: “lein test”, which does nothing)
I’ll follow up
Cheers
Jan

**Comment by jsulmont** [comment]
Greetings

Just submitted another pull request, fixing tests and also a minor bug due to using method deprecated in Antler 4.4.x :) Tests pass just fine
I’m now going to re-write my Orc https://orc.csres.utexas.edu/research.shtml compiler in Clojure (from Java) — still using Antlr4. Of course I’ll follow up if anything comes up.
I’ve got an Orc virtual machine, distributed, C++, etc etc. I love distributed systems, synchronous languages. … and Clojure <3

Thanks a lot for your work.

Jan

—

Compiling 2 source files to /Users/jan/tmp/clj-antlr/target/classes

lein test clj-antlr.core-test
"Elapsed time: 9969.506857 msecs"

lein test clj-antlr.perf-test
Benchmarking instaparse
Evaluation count : 780 in 60 samples of 13 calls.
             Execution time mean : 91.901752 ms
    Execution time std-deviation : 8.499992 ms
   Execution time lower quantile : 83.723919 ms ( 2.5%)
   Execution time upper quantile : 117.407982 ms (97.5%)
                   Overhead used : 9.629488 ns

Found 3 outliers in 60 samples (5.0000 %)
        low-severe       1 (1.6667 %)
        low-mild         2 (3.3333 %)
 Variance from outliers : 66.9118 % Variance is severely inflated by outliers

Benchmarking clj-antlr
Evaluation count : 79080 in 60 samples of 1318 calls.
             Execution time mean : 807.294316 µs
    Execution time std-deviation : 50.373737 µs
   Execution time lower quantile : 749.726647 µs ( 2.5%)
   Execution time upper quantile : 917.465085 µs (97.5%)
                   Overhead used : 9.629488 ns

Found 2 outliers in 60 samples (3.3333 %)
        low-severe       2 (3.3333 %)
 Variance from outliers : 46.7708 % Variance is moderately inflated by outliers

Ran 8 tests containing 200014 assertions.
0 failures, 0 errors.

**Comment by aphyr** [comment]
Thanks for fixing those! Tests pass here too, and I've released 0.2.3 to Clojars for you. Glad to hear clj-antlr has been helpful!

**Comment by jsulmont** [comment]
Groovy!

**Pull request merged**
